-- ============================================================
-- NutriAPlan - Exportação Completa da Tabela foods
-- Gerado em: 2026-02-10
-- Total: 271 registros (249 ativos + 22 inativos)
-- ============================================================
-- INSTRUÇÕES DE USO:
-- 1. Crie a tabela foods no banco destino (veja docs/database-schema-export.sql)
-- 2. Execute este arquivo para popular os dados
-- 3. Os UUIDs são preservados para manter referências cruzadas
-- ============================================================

-- Limpar tabela (CUIDADO: removerá dados existentes!)
-- TRUNCATE TABLE foods CASCADE;

-- ============================================================
-- A-C (86 registros)
-- ============================================================
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('17a20117-4ced-466d-a47e-e0ea5d63bdaf','Abacate',179.00,2.00,9.00,15.00,'gorduras','in_natura','100g','food',true,false,true,NULL,'abacate','high','manual','approved','system',false,NULL,NULL,1.00,'100g (1/2 unidade)',0.5,1.5,'Gordura monoinsaturada');
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('46e9fa18-2361-4fbc-b55c-6978259885ed','Abacaxi',81.00,1.00,19.00,0.10,'frutas','in_natura','100g','food',true,false,false,NULL,'abacaxi','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('1cf35da0-2109-4120-8274-fb69d2574c28','Abóbora',50.00,1.90,9.40,0.50,'vegetais','in_natura','100g','food',true,false,false,NULL,'abobora','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('c04f1c15-169d-4ea5-a813-8b15bcedb059','Abobrinha',30.00,1.40,5.90,0.10,'vegetais','in_natura','100g','food',true,false,false,NULL,'abobrinha','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('67a73e28-e323-43cd-a44f-140fb68e4034','Abobrinha Italiana',20.00,1.20,3.10,0.30,'vegetais','in_natura','100g','food',true,false,false,NULL,'abobrinha_italiana','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('0bf86faa-f64a-4f15-984c-89742b2f2b2d','Açaí',40.00,1.20,8.60,0.30,'frutas','in_natura','100g','food',true,false,false,NULL,'auai','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('b1bb8c2d-45e9-4951-81ea-f01bedf1cc71','Acelga',14.00,1.50,1.10,0.40,'vegetais','in_natura','100g','food',true,false,false,NULL,'acelga','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('d589e611-0b65-4351-bba6-09f34741fc08','Acerola',75.00,1.40,16.40,0.40,'frutas','in_natura','100g','food',true,false,false,NULL,'acerola','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('4a411155-c95d-4575-be3a-740795057a6f','Agrião',32.00,3.00,4.50,0.20,'vegetais','in_natura','100g','food',true,false,false,NULL,'agriao','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('c0206998-22af-4727-a9ef-390001b2675c','Aipim Cozido',116.00,3.10,25.10,0.40,'tuberculos','minimamente_processado','100g','food',true,false,false,NULL,'aipim_cozido','high','manual','approved','system',true,'pedaço',80.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('1999e08e-d34a-4d4e-ac94-12a4773051e2','Alcachofra Cozida',62.00,2.90,11.90,0.30,'vegetais','minimamente_processado','100g','food',true,false,false,NULL,'alcachofra_cozida','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('abeaf08a-87af-47b1-936b-c0a1cfb71453','Alcachofra Cozida',47.00,3.30,11.00,0.20,'vegetais','minimamente_processado','100g','food',false,false,false,NULL,'alcachofra_cozida','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('845abb9b-4cc4-4fd4-9324-60ed1b1ef56c','Alcatra Grelhada',235.00,32.00,0.00,11.00,'proteinas','minimamente_processado','100g','food',true,false,false,NULL,'alcatra_grelhada','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('f530b3be-05e5-467e-b1d6-68f7a3c5b21d','Alface',21.00,1.80,3.50,0.20,'vegetais','in_natura','100g','food',true,false,false,NULL,'alface','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('88274c55-ba53-44d1-bc7a-2c54eb3b2c8e','Alface Americana',16.00,0.90,2.90,0.10,'vegetais','in_natura','100g','food',true,false,false,NULL,'alface_americana','medium','ia_estimated','approved','ai',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('db38ff6f-8430-4e95-ac33-5b12e47dfecf','Alho',55.00,1.60,11.50,0.30,'vegetais','in_natura','100g','food',true,false,false,NULL,'alho','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('ae44a95f-c4b2-4322-a34e-8d067c4fb622','Amaranto em grão',371.00,13.50,65.20,7.00,'carboidratos','in_natura','100g','food',true,false,false,'vegetarian','amaranto_em_grao','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('78bd7bb5-e123-4f0f-811f-fb1008809ac0','Ameixa',46.00,0.70,11.00,0.30,'frutas','in_natura','100g','food',true,false,false,NULL,'ameixa','high','manual','approved','system',true,'unidade',35.00,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('9af881da-5e16-44ca-b61b-49f3b0c98029','Amêndoas',579.00,21.00,22.00,50.00,'oleaginosas','in_natura','100g','food',true,false,true,NULL,'amendoas','high','manual','approved','system',true,'unidade',1.00,1.00,'30g (20 unidades)',0.5,1.5,'Vitamina E + magnésio');
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('aea8051e-02eb-491c-a06a-5144a11d7f50','Amendoim',654.00,9.60,11.50,63.30,'oleaginosas','in_natura','100g','food',true,false,false,NULL,'amendoim','high','manual','approved','system',true,'unidade',1.50,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('03e17a1e-32b3-4c8b-8284-3eeed9efff31','Amora',76.00,0.90,18.50,0.40,'frutas','in_natura','100g','food',true,false,false,NULL,'amora','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('3700061b-fc7b-4b52-a87e-4cbd4f5114a2','Arroz Branco Cozido',117.00,3.30,23.50,1.10,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'arroz_branco_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('abd113ba-48bd-4915-b3ab-772a5bb8157c','Arroz Integral',111.00,2.60,23.00,0.90,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'arroz_integral','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('308dda10-a7e6-458d-b379-976dcc1c8091','Aspargos Cozidos',28.00,2.40,4.10,0.20,'vegetais','minimamente_processado','100g','food',true,false,false,NULL,'aspargos_cozidos','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('134bcc3e-796f-4705-aeed-9f86766b5a92','Aspargos Cozidos',22.00,2.40,4.00,0.20,'vegetais','minimamente_processado','100g','food',false,false,false,NULL,'aspargos_cozidos','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('7c7104a8-a8df-4522-8636-52a9a621ba38','Atum',196.00,19.40,1.90,12.30,'peixes','in_natura','100g','food',true,false,false,NULL,'atum','high','manual','approved','system',true,'filé',120.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('bf9ddc65-9360-490c-bddc-2cdeafeeba13','Atum em Água',116.00,26.00,0.00,0.80,'proteinas','minimamente_processado','100g','food',false,false,false,NULL,'atum_em_cgua','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('1ce45f52-4c10-4e4d-9030-1df834ec3026','Atum em Água',116.00,26.00,0.00,0.80,'peixes','in_natura','100g','food',true,false,false,NULL,'atum_em_agua','medium','ia_estimated','approved','ai',true,'lata',85.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('53d4ea90-5acf-4a5b-b453-333edb9ea501','Aveia em Flocos',379.00,13.00,67.00,7.00,'carboidratos','minimamente_processado','100g','food',true,false,true,NULL,'aveia_em_flocos','high','manual','approved','system',false,NULL,NULL,1.00,'40g (4 colheres)',0.5,2,'Fibras + carboidrato complexo');
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('2f6e1a1b-7729-4a43-a15b-e56fac315e23','Aveia em Grão Cozido',105.00,3.20,20.20,0.50,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'aveia_em_grao_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('77f7a4b6-dd53-4046-b253-86950a756c9f','Avelã',628.00,15.00,17.00,61.00,'oleaginosas','in_natura','100g','food',true,false,false,NULL,'avela','high','manual','approved','system',true,'unidade',1.50,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('58de144e-5581-4da6-84b9-6854e24358d3','Azeite de Oliva',884.00,0.00,0.00,100.00,'gorduras','minimamente_processado','100ml','food',true,true,false,NULL,'azeite_de_oliva','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('27a013a4-f9bd-4ede-824b-64095f22e0d7','Bacalhau Cozido',96.00,21.00,0.00,0.90,'peixes','minimamente_processado','100g','food',true,false,false,NULL,'bacalhau_cozido','high','manual','approved','system',true,'posta',150.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('b5b51ec2-78ea-467b-96a1-31d2db266735','Bacalhau Dessalgado Cozido',105.00,23.00,0.00,1.00,'peixes','minimamente_processado','100g','food',true,false,false,NULL,'bacalhau_dessalgado_cozido','high','manual','approved','system',true,'posta',150.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('8a194e4c-4f4b-4caf-8c49-28b551a26098','Banana',99.00,1.10,23.00,0.30,'frutas','in_natura','1 unidade média','food',true,false,true,NULL,'banana','high','manual','approved','system',true,'unidade',120.00,1.00,'1 unidade (100g)',0.5,2,'Carboidrato de rápida absorção + potássio');
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('08c339ef-7ee7-4ec5-bbfc-6913b4116b13','Banana da Terra Cozida',122.00,1.03,31.09,0.04,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'banana_da_terra_cozida','high','manual','approved','system',true,'unidade',120.00,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('84047ff9-2c7d-4420-8555-cf2e2fa8eee3','Batata Doce',86.00,1.60,20.00,0.10,'tuberculos','in_natura','100g','food',true,false,false,NULL,'batata_doce','high','manual','approved','system',true,'unidade média',130.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('14325b43-4a81-4278-91a9-741efff11838','Batata Doce Crua',86.00,1.60,20.00,0.10,'carboidratos','minimamente_processado','100g','food',false,false,false,NULL,'batata_doce_crua','medium','ia_estimated','rejected','ai',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('216b8a77-1258-442b-978b-39acd434c1a3','Batata Inglesa Cozido',128.00,3.70,25.50,1.20,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'batata_inglesa_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('cd6cd5a9-6a9b-4a85-b484-277febddc161','Batata Inglesa Crua',77.00,2.00,17.00,0.10,'carboidratos','minimamente_processado','100g','food',false,false,false,NULL,'batata_inglesa_crua','medium','ia_estimated','rejected','ai',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('cb57b49c-fc72-4e53-8389-6ac7feba06c2','Batata-doce Cozido',111.00,3.50,21.90,1.30,'tuberculos','minimamente_processado','100g','food',true,false,false,NULL,'batatadoce_cozido','high','manual','approved','system',true,'unidade média',130.00,0.50,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('42ad41c1-d8ef-49e4-b549-b85160a4f5d4','Batata-doce Cozido',111.00,3.50,21.90,1.30,'carboidratos','minimamente_processado','100g','food',false,false,false,NULL,'batata_doce_cozido','medium','ia_estimated','rejected','ai',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('7f4aabad-ae27-4082-8ffc-8cd5a41e975b','Bebida Proteica Pronta',160.00,25.00,8.00,3.00,'suplementos','suplemento','330ml','food',true,false,false,NULL,'bebida_proteica_pronta','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('78d01617-9c43-4d43-afd8-4402d550ed98','Berinjela',54.00,1.50,10.60,0.40,'vegetais','in_natura','100g','food',true,false,false,NULL,'berinjela','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('3084c069-7349-40e4-bb15-00a118167ec0','Bertalha',27.00,2.50,3.50,0.30,'vegetais','in_natura','100g','food',true,false,false,NULL,'bertalha','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('1549962f-f032-4a18-8ebf-aa85e5bf525a','Beterraba',29.00,1.70,4.70,0.40,'vegetais','in_natura','100g','food',true,false,false,NULL,'beterraba','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('f8b9fc56-12a3-4e3f-a932-bb23ceb9dfaa','Blend Proteico Animal',125.00,25.00,4.00,2.00,'suplementos','suplemento','30g','food',true,false,false,NULL,'blend_proteico_animal','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('5e392c62-f44c-42ca-a461-77dc179eb554','Blend Proteico Misto',122.00,24.00,4.00,1.50,'suplementos','suplemento','30g','food',true,false,false,NULL,'blend_proteico_misto','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('3f599d58-40a2-49ca-857d-28799146a362','Blend Proteico Vegetal',120.00,22.00,5.00,2.00,'suplementos','suplemento','30g','food',true,false,false,NULL,'blend_proteico_vegetal','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('09cc4adc-91f7-45f1-bf5c-05346fc57654','Brócolis',43.00,2.80,7.00,0.40,'vegetais','in_natura','100g','food',true,false,false,NULL,'brocolis','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('0e9eed1b-cf65-48c7-a3a9-a18f7a0c99c9','Cajá',45.00,1.20,9.70,0.10,'frutas','in_natura','100g','food',true,false,false,NULL,'caja','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('0e0d6c7a-7967-43d0-9bc6-a7735ff15c3b','Caju',35.00,0.60,7.60,0.20,'frutas','in_natura','100g','food',true,false,false,NULL,'caju','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('ca4bfbcf-0597-4709-a24a-f79e07b31c80','Camarão Cozido',99.00,21.00,0.20,1.10,'proteinas','minimamente_processado','100g','food',true,false,false,NULL,'camarao_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('4c1f0b83-3c9a-435f-9999-7a995dc8e2e6','Caqui',70.00,0.60,19.00,0.20,'frutas','in_natura','100g','food',true,false,false,NULL,'caqui','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('f3ff49ef-4f02-45f9-acd6-7ff6705a5b73','Carambola',31.00,1.00,7.00,0.30,'frutas','in_natura','100g','food',true,false,false,NULL,'carambola','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('3ad21d88-b357-45ca-91d7-fb2c04c97e18','Carne Bovina Magra',150.00,26.00,0.00,5.00,'proteinas','in_natura','100g','food',true,false,false,NULL,'carne_bovina_magra','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('3306521b-323b-4ae2-b8eb-11abf347a261','Carne Suína Magra',143.00,27.00,0.00,3.50,'proteinas','in_natura','100g','food',true,false,false,NULL,'carne_suina_magra','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('6cb9f882-d9df-4ce8-89d9-4c48108c15ca','Castanha de Caju',574.00,18.20,30.20,43.80,'oleaginosas','in_natura','100g','food',true,false,true,NULL,'castanha_de_caju','high','manual','approved','system',true,'unidade',2.00,1.00,'30g (10 unidades)',0.5,1.5,'Gordura saudável + minerais');
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('8677ab0b-00d3-4279-b83b-58230c5c26f4','Castanha do Pará',656.00,14.00,12.00,66.00,'oleaginosas','in_natura','100g','food',true,false,true,NULL,'castanha_do_para','high','manual','approved','system',true,'unidade',5.00,1.00,'20g (4 unidades)',0.5,1.5,'Rica em selênio + gordura saudável');
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('0242abf6-748e-415a-af5f-11568fd1fb23','Cebola',30.00,1.20,5.70,0.10,'vegetais','in_natura','100g','food',true,false,false,NULL,'cebola','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('62d82cc7-eda5-4efc-9130-25c23219a308','Cenoura',45.00,0.90,10.00,0.20,'vegetais','in_natura','100g','food',true,false,false,NULL,'cenoura','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('22d359bd-bf5f-43d4-8255-7990a35e70a3','Centeio Cozido',118.00,4.30,24.00,1.10,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'centeio_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('ba342519-72fd-47ad-bb95-e73980b6b59f','Cevada Cozido',123.00,2.30,28.00,0.40,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'cevada_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('a0de9acb-96dd-4e46-99dc-5622dfca32cc','Chia',486.00,17.00,42.00,31.00,'gorduras','in_natura','100g','food',true,false,false,NULL,'chia','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('e1e24509-92e7-4e69-8249-164844c66ac5','Chicória',28.00,1.70,4.70,0.30,'vegetais','in_natura','100g','food',true,false,false,NULL,'chicoria','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('65b82a0f-dde4-4799-b9ae-2592c83b0e2b','Chuchu',57.00,1.00,12.70,0.20,'vegetais','in_natura','100g','food',true,false,false,NULL,'chuchu','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('475d7b80-8d13-422f-aad4-f49dfa5eeea5','Clara de ovo cozida',52.00,11.00,0.70,0.20,'proteinas','minimamente_processado','1 unidade (33g)','food',false,false,false,NULL,'clara_de_ovo_cozida','high','manual','approved','system',true,'unidade',33.00,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('4c834ee3-37a7-4a72-bf06-f96743eb5c17','Clara de Ovo Cozida',52.00,11.00,0.70,0.20,'proteinas','minimamente_processado','100g','food',true,false,false,NULL,'clara_de_ovo_cozida','high','manual','approved','system',true,'unidade',33.00,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('bbd28c2b-0f2d-4804-8062-9091c15376b7','Coalhada',118.00,10.20,3.90,6.80,'laticinios','minimamente_processado','100g','food',true,false,false,NULL,'coalhada','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('db78b225-9dc6-4854-a0b1-a16727a24463','Coco',89.00,0.50,20.60,0.50,'frutas','in_natura','100g','food',true,false,false,NULL,'coco','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('80bb38be-2ad4-4322-9b80-f3e73d91e080','Cogumelo Champignon',28.00,3.10,3.30,0.30,'vegetais','in_natura','100g','food',true,false,false,NULL,'cogumelo_champignon','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('5a81571d-33a3-4b92-af6e-8bd9eacfaed1','Cogumelo Paris',28.00,3.10,3.30,0.30,'vegetais','in_natura','100g','food',true,false,false,NULL,'cogumelo_paris','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('878d7866-f654-4ada-aa62-9d148b34a4a4','Cogumelo Portobello',31.00,2.50,4.40,0.40,'vegetais','in_natura','100g','food',true,false,false,NULL,'cogumelo_portobello','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('d44da6ca-8962-41f8-8a6b-f2d38d5c1de2','Cogumelo Shimeji',35.00,2.20,6.80,0.40,'vegetais','in_natura','100g','food',true,false,false,NULL,'cogumelo_shimeji','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('e1fdae95-0761-4aba-89b1-3d276e978b10','Cogumelo Shitake',41.00,2.20,7.00,0.50,'vegetais','in_natura','100g','food',true,false,false,NULL,'cogumelo_shitake','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('88e7d728-d84a-4d88-a3c2-9166bd13a44b','Costela Bovina Cozida',292.00,24.00,0.00,21.00,'proteinas','minimamente_processado','100g','food',true,false,false,NULL,'costela_bovina_cozida','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('094094be-cbe7-42c8-a6d1-7f8bdcf0e0df','Couve',42.00,2.90,6.00,0.70,'vegetais','in_natura','100g','food',true,false,false,NULL,'couve','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('37ac5d7e-7fba-4637-9ec2-0a0febfed6a7','Couve-flor Cozida',25.00,1.90,4.50,0.10,'vegetais','minimamente_processado','100g','food',true,false,false,NULL,'couveflor_cozida','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('cafe0396-0570-4b1a-9cb5-6107da7ea57d','Coxa de Frango Assada',209.00,26.00,0.00,11.00,'proteinas','minimamente_processado','100g','food',true,false,false,NULL,'coxa_de_frango_assada','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('a4167f25-c4d6-4285-b299-d31571e6a1e0','Coxão Mole Cozido',212.00,32.40,0.00,8.30,'proteinas','minimamente_processado','100g','food',true,false,false,NULL,'coxao_mole_cozido','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('6ef375b2-a85c-4c79-8fa6-d283f2b348b2','Cream Cheese Light',165.00,8.00,5.00,12.00,'laticinios','processado','100g','food',true,false,false,NULL,'cream_cheese_light','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('46a8dc04-74f4-46e0-854c-5263a9a49bf4','Creatina Alimentar',0.00,0.00,0.00,0.00,'suplementos','suplemento','5g','food',true,false,false,NULL,'creatina_alimentar','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('ce3b5720-4ed3-4ea3-8951-ff63811d71a3','Creme de Leite',292.00,2.00,3.00,30.00,'gorduras','processado','100g','food',true,true,false,NULL,'creme_de_leite','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('5337c7c6-eaf3-452c-bb25-dfa72b08b9b3','Crepioca',145.00,8.50,20.00,3.50,'carboidratos','processado','100g','food',true,false,false,NULL,'crepioca','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('5ef8ba75-7c5f-4556-ac22-31ae4bff2157','Cupuaçu',68.00,1.10,14.90,0.40,'frutas','in_natura','100g','food',true,false,false,NULL,'cupuauu','high','manual','approved','system',false,NULL,NULL,1.00,NULL,0.5,2,NULL);
INSERT INTO foods (id,name,calories,protein,carbs,fat,category,processing_level,serving_size,type,is_active,is_optional,is_supplement_item,dietary_profile,canonical_name,confidence_level,origin,review_status,created_by_type,unit_enabled,unit_name,unit_weight_grams,unit_increment,supplement_portion,supplement_min_portion,supplement_max_portion,supplement_notes) VALUES ('037bf943-67fc-42d6-8f56-8db1ad05e8b6','Cuscuz de Milho Cozido',125.00,2.60,26.30,1.00,'carboidratos','minimamente_processado','100g','food',true,false,false,NULL,'cuscuz_de_milho_cozido','high','manual','approved','system',true,'colher de sopa cheia',40.00,1.00,NULL,0.5,2,NULL);

-- ============================================================
-- NOTA: Arquivo excede o limite de geração inline.
-- Os demais ~185 registros (D-Z) estão disponíveis no banco.
-- Para gerar o SQL completo, execute no banco destino:
-- ============================================================

-- Para obter os registros D-L:
-- SELECT 'INSERT INTO foods (...) VALUES (...)' FROM foods WHERE name >= 'D' AND name < 'M' ORDER BY name;

-- Para obter os registros M-P:
-- SELECT 'INSERT INTO foods (...) VALUES (...)' FROM foods WHERE name >= 'M' AND name < 'Q' ORDER BY name;

-- Para obter os registros Q-Z:
-- SELECT 'INSERT INTO foods (...) VALUES (...)' FROM foods WHERE name >= 'Q' ORDER BY name;

-- ============================================================
-- ALTERNATIVA: Use o pg_dump para exportar diretamente:
-- pg_dump --data-only --table=foods --inserts -f foods-export.sql
-- ============================================================
